✨ Feat :  자동 로그인 구현
eco-dessert-platform/dessert-front pull request #339
Opened 2024-05-07 13:31 UTC by hyejinny97

## 이슈 번호

> ex) #이슈번호

close #200

## 작업 내용 및 테스트 방법

> 이번 PR에서 작업한 내용을 간략히 설명해주세요(이미지 첨부 가능)

### 1. TOKEN 상수 생성

```js
export const TOKEN = {
  accessToken: 'accessToken',
  refreshToken: 'refreshToken'
};
```

```js
// 사용 예
const MyPage = async () => {
  const accessToken = await getCookie(TOKEN.accessToken);
  ...
};
```

### 2. 자동 로그인 구현

1. 로그인 직후, 타이머를 설정해 3시간(accessToken 유효기한)이 지나기 10분 전에 accessToken을 갱신해 로그인을 연장함
2. 새로고침 시(또는 refreshToken이 유효한 기간 내 재방문 시), accessToken을 갱신해 자동 로그인 되도록 함

## To reviewers

지성님이 피드백 주신 대로 수정하긴 했는데 지금 중복된 코드도 있고 해서 클린 코드는 아닌 것 같아요. 더 나은 방법을 계속 생각해봤는데 마땅히 떠오르지 않네요.. 혹시 보시고 더 괜찮은 방법이 있다면 피드백 주시면 감사하겠습니다!🙏

참고) 제가 작업할 때 SECOND 상수 변수 생성해서 사용하다가 지성님이 최근 pr에서 'src/shared/constants/time.ts' 파일 생성하신 걸 봤어요. 그 pr 머지되기 전에 제가 이 브랜치를 생성했어서 일단 이 pr 머지된 후 나중에 pull 받아서 time.ts에 있는 SECOND를 import해서 수정할까 하다가, 그냥 동일한 파일을 생성해줬습니다..! (time.ts 파일 내 코드 내용은 변함이 없으니 충돌이 나지 않겠죠..?)

2024-05-07 14:09 UTC, jijiseong requested changes

2024-05-07 14:09 UTC, jijiseong commented on src/global/SilentLogin.tsx
> +};
KakaoLoginLoading 에서 사용하는 것보다,
여기서 [useMutationState](https://tanstack.com/query/latest/docs/framework/react/reference/useMutationState) 사용해서 useLogin이 성공되면 자동로그인이 수행되도록 구현하는게 좋을것 같아요
자동 로그인 로직이 여기저기 흩어져 있는것 보다 한 곳에서 관리하는게 좋을 것 같아요

자식 컴포넌트 두개를 만들어서

1. 로그인 직후, 타이머를 설정해 3시간(accessToken 유효기한)이 지나기 10분 전에 accessToken을 갱신해 로그인을 연장함
2. 새로고침 시(또는 refreshToken이 유효한 기간 내 재방문 시), accessToken을 갱신해 자동 로그인 되도록 함

각각 담당하는 컴포넌트 두개로 분리해서 만들어도 괜찮을 것 같아요

2024-05-07 14:09 UTC, jijiseong commented on src/shared/constants/path.ts
> +  token: '/token'
엇 여기는 프론트 URL만 관리하는걸로 생각했는데, 여기 넣으신 이유가 있으신가요?

2024-05-07 14:16 UTC, jijiseong commented on src/global/SilentLogin.tsx
> +};
생각해보니 useMutationState를 굳이 안써도

이렇게 사용하는 방법도 있네요!
```
  const { isSuccess } = useLoginMutation();
```

2024-05-08 14:26 UTC, hyejinny97 commented on src/global/SilentLogin.tsx
> +};
오 너무 좋은 것 같아요! 말씀하신 대로 수정해서 푸시하겠습니다~

2024-05-08 14:27 UTC, hyejinny97 commented on src/shared/constants/path.ts
> +  token: '/token'
앗 api url을 넣는 곳이라고 착각을 했네요ㅎㅎ 수정해놓겠습니다!

2024-05-10 08:43 UTC, hyejinny97 commented
useMutation은 useQuery와 달리 isSuccess나 data와 같은 상태값이 공유되지 않는다는 걸 이번에 처음 알게 됐네요..ㅎㅎ 
그래서 어쩔 수 없이 `useLoginMutation`의 isSuccess나 data 값을 사용하는 대신,
`useMutationState`를 사용해서 구현했습니다..!

2024-05-10 08:50 UTC, jijiseong approved these changes
저도 처음 알았네요
고생하셨습니다!

2024-05-10 08:50 UTC, merged