♻️ Refactor :  스토어 상세 api 응답 수정
eco-dessert-platform/dessert-front pull request #352
Opened 2024-05-11 14:57 UTC by Wlfjd

## 이슈 번호

> #

## 작업 내용 및 테스트 방법

>

스토어 상세 페이지 api 응답 리팩토링하였습니다.
(+ 이 부분 제가 맡기로 했었는데 요 몇일 브랜치 커밋내역 때문에 끙끙대다가 누락되었었던 것 같아요!ㅠ 죄송합니다)

## To reviewers

2024-05-12 09:17 UTC, hyejinny97 requested changes

2024-05-12 09:17 UTC, hyejinny97 commented on src/domains/store/hooks/useGetStoreDetailAllQuery.ts
>    if (!res.ok) throw new Error('상품 상세 조회 실패');
10번줄 코드는 삭제하셔도 될 것 같습니다!

2024-05-12 10:05 UTC, jijiseong commented
pr check github action 에서 오류난거 같아서 수정해서 develop에 머지했는데, 
pull 받고 push 해주세요!

2024-05-13 14:24 UTC, Wlfjd commented
> pr check github action 에서 오류난거 같아서 수정해서 develop에 머지했는데, pull 받고 push 해주세요!

풀받고 푸쉬했는데 또 오류가 나는 것 같습니다ㅜ

2024-05-14 06:12 UTC, jijiseong commented
혹시 yarn install 하면 yarn.lock 파일 수정 되는지 확인해봐주실래요?
바뀐다면 push 해주세요!

2024-05-14 12:10 UTC, Wlfjd commented
> 혹시 yarn install 하면 yarn.lock 파일 수정 되는지 확인해봐주실래요? 바뀐다면 push 해주세요!

yarn install을 했을 때 yarn.lock 파일이 수정되지 않네요ㅜㅜ (참고로 브랜치가 꼬인 문제때문에 새로 clone 받았습니다)

2024-05-14 12:21 UTC, hyejinny97 commented
음 그러면 그냥 이 pr close하고 다시 API 수정하신 후 pr 올리면 어떨까요??
수정해야할 부분이 많지 않아서 금방 작업하실 수 있을 것 같아요!

2024-05-14 12:29 UTC, closed without merging