✨ Feat :  `StarRating` 컴포넌트 생성
eco-dessert-platform/dessert-front pull request #360
Opened 2024-05-14 12:02 UTC by hyejinny97

## 이슈 번호

> ex) #이슈번호

close #357 

## 작업 내용 및 테스트 방법

> 이번 PR에서 작업한 내용을 간략히 설명해주세요(이미지 첨부 가능)

### 1. `StarRating` 컴포넌트 생성

```js
interface StarRatingProps {
  initRating?: 0 | 1 | 1.5 | 2 | 2.5 | 3 | 3.5 | 4 | 4.5 | 5;  // 초기 점수 (default=0)
  size?: 'small' | 'large';  // 각각 20x20, 48x48 크기 별 (default='small')
  dragged?: boolean;  // 드래그 및 클릭 가능 여부 (default=false)
}
```

### 2. `StarRating` 스토리 생성

![review-star-rating](https://github.com/eco-dessert-platform/dessert-front/assets/98448226/00a513ec-98d6-4c44-805f-35ad400a8820)

## To reviewers

2024-05-14 12:23 UTC, Wlfjd commented on src/domains/review/components/StarRating/index.tsx
> +    setRating(Number(e.target.value) as RatingType);
` as RatingType` 을 해주시는 이유가 뭔가요?? as는 타입 단언이라고 알고 있는데, 여기서 타입 단언이 되야하는 이유가 궁금해요!

2024-05-14 13:08 UTC, hyejinny97 commented on src/domains/review/components/StarRating/index.tsx
> +    setRating(Number(e.target.value) as RatingType);
rating state의 type은 `0 | 1 | 1.5 | 2 | 2.5 | 3 | 3.5 | 4 | 4.5 | 5`으로 union type이고
`Number(e.target.value)`은 number type여서 타입 에러가 뜨더라구요. 
그래서 `as`를 사용해 타입을 맞춰주었습니다!

2024-05-14 22:03 UTC, jijiseong requested changes

2024-05-14 22:03 UTC, jijiseong commented on src/domains/review/components/StarRating/index.tsx
> +      />
className에 absoulte랑 opacity 사용한 이유가 뭔가요?
숨기려고 그런거면 hidden인가 invisible인가 쓰면 되지 않나요?

2024-05-14 22:03 UTC, jijiseong commented on src/domains/review/components/StarRating/index.tsx
> +      <Stars rating={rating} size={size} />
div 보다 label을 사용하는게 적합할거같아요

2024-05-14 22:27 UTC, jijiseong commented on src/domains/review/components/StarRating/index.tsx
> +}
그리고 draggable 보다는
editable 이 괜찮지 않을까요?

(draggable로 바꾼 커밋은 있는데 dragged라고 되어있네요 🧐)

2024-05-15 06:08 UTC, Wlfjd commented on src/domains/review/components/StarRating/index.tsx
> +      <Stars rating={rating} size={size} />
이유가뭔가요?? input 과 함께 사용되어서 그런건가요? 저는 label엔 텍스트가 들어가는게 더 익숙하다고 느껴져서 질문드립니다!

2024-05-16 09:36 UTC, jijiseong commented on .eslintrc.json
> +    ],
린트 설정 왜 바꿨나요?

2024-05-16 09:36 UTC, jijiseong commented on src/domains/review/components/StarRating/index.tsx
> +        id="starRating"
useId 훅 쓰는게 좋아보입니다!

2024-05-16 09:44 UTC, hyejinny97 commented on .eslintrc.json
> +    ],
div -> label로 수정했더니 아래와 같은 에러가 떠서 변경해줬습니다~
```
A form label must be associated with a control.eslint[jsx-a11y/label-has-associated-control](https://github.com/jsx-eslint/eslint-plugin-jsx-a11y/blob/main/docs/rules/label-has-associated-control.md)
```

2024-05-16 09:48 UTC, jijiseong commented on .eslintrc.json
> +    ],
이것도 웹 접근성 관련 린트인데, 끄면 안돼요
label에 텍스트가 없고 아이콘만 있어서 그런거같은데
```tsx
<label aria-label="별점"/>
```
이런식으로 넣어주면 됩니다.

2024-05-16 09:51 UTC, hyejinny97 commented on .eslintrc.json
> +    ],
아.. 텍스트가 없어서 그런 거였군요...! 다시 수정해 놓겠습니다!

2024-05-16 10:13 UTC, jijiseong approved these changes
고생하셨어요!

2024-05-16 10:13 UTC, merged