✨ Feat : 리뷰 작성/수정 페이지 퍼블리싱
eco-dessert-platform/dessert-front pull request #374
Opened 2024-05-21 14:24 UTC by hyejinny97

## 이슈 번호

> ex) #이슈번호

## 작업 내용 및 테스트 방법

> 이번 PR에서 작업한 내용을 간략히 설명해주세요(이미지 첨부 가능)

### 리뷰 작성 페이지

<image src='https://github.com/eco-dessert-platform/dessert-front/assets/98448226/14f2e81a-07fd-4c49-8b94-2a97fbd02ae4' width='600px' />

### 리뷰 수정 페이지

<image src='https://github.com/eco-dessert-platform/dessert-front/assets/98448226/87e0e824-c91d-403f-a5eb-b0d72289374d' width='600px' />

## To reviewers

@Wlfjd 현재 상품 상세 페이지에서 `getProductDetail`을 통해서 데이터를 가져오고 있던데, 
useQuery를 사용해서 '상품 상세 데이터'를 가져오는 `useGetProductDetailQuery`를 새로 하나 생성했습니다. 
상품 상세 페이지에서 상품/스토어 찜 성공 시 데이터를 refetch 해서 싱크를 맞춰줘야 한다고 생각하기 때문에,
`getProductDetail`보다는 `useGetProductDetailQuery`를 사용하는 것이 좋을 것 같습니다!

2024-05-22 07:30 UTC, jijiseong requested changes

2024-05-22 07:30 UTC, jijiseong commented on src/app/main/(detail)/products/[productId]/review/create/page.tsx
> +      </form>
BadgeSelectPage
StarRatingSelectPage
컴포넌트들을 병렬 라우팅 하는건 어떨까요

Page라는 네이밍이 blocks 폴더랑은 맞지 않는것 같아서요

2024-05-22 07:30 UTC, jijiseong commented on src/app/main/(detail)/products/[productId]/review/create/page.tsx
> +      </form>
그리고 blocks랑 app 폴더 구조는 1대1로 매칭 해야해요

2024-05-22 07:30 UTC, jijiseong commented on src/blocks/review/StarRatingSelectPage/ButtonSection.tsx
> +    <div className="fixed z-[5000] left-1/2 -translate-x-1/2 bottom-0 w-full max-w-[600px] bg-white">
zindex는 tailwind config에서 관리하는게 좋아보여요

2024-05-22 07:30 UTC, jijiseong commented on src/domains/review/components/PreviewImage.tsx
PreviewImage는 
blocks/review/StarRatingSelectPage/ImageUploadSection
에서만 사용되는 재사용성 없는 컴포넌트라 
ImageUploadSection 폴더로 옮겨야할 것 같아요

2024-05-23 05:51 UTC, hyejinny97 commented on src/app/main/(detail)/products/[productId]/review/create/page.tsx
> +}
현재 `ReviewCreatePage`에서 progress prop을 받아서 하위 컴포넌트로 내려 주고 있지 않은데 props drilling이라고 말씀하시는 이유가 있으실까요??

2024-05-23 05:52 UTC, hyejinny97 commented on src/blocks/review/StarRatingSelectPage/StarRatingSection.tsx
> +  const { data } = useGetProductDetailQuery(productId as string);
오 이렇게 간단한 방법이 있었군요..

2024-05-23 05:58 UTC, hyejinny97 commented on src/domains/product/queries/useGetProductDetailQuery.ts
> +  };
지성님이 노션에 Service 관련해서 작성해주신 부분 아직 자세히 읽어 보지 못해서요..!
일단 퍼블리싱 먼저 빠르게 구현해야겠단 생각에 이 부분은 기존 방식으로 작성했습니다.
제가 내일이나 내일 모레쯤 노션에 작성해주신 부분 읽어보고 리뷰 작성 페이지 API 연동하려고 하는데,
그때 이 부분도 같이 수정해서 pr 올리겠습니다!

2024-05-23 06:01 UTC, hyejinny97 commented on src/domains/review/types/badge.ts
> +}
리뷰 작성 페이지에서 배지를 선택하지 않은 초기 상태일 때를 표현하기 위해 `undefined`를 타입에 추가했습니다.
지금 보니 `undefined`보다는 `null`이 더 적절한 것 같네요.

2024-05-23 12:50 UTC, Wlfjd commented on src/app/main/(detail)/products/[productId]/review/create/layout.tsx
> +      <form onSubmit={handleFormSubmit}>{progress === '1' ? badgeSelect : starRatingSelect}</form>
badgeSelect , starRatingSelect을 이 파일에서 import하지 않으신 이유가 궁금합니다

2024-05-23 13:29 UTC, jijiseong approved these changes
고생하셨어요!

2024-05-24 06:08 UTC, hyejinny97 commented on src/app/main/(detail)/products/[productId]/review/create/@badgeSelect/page.tsx
1. `page.tsx`의 컴포넌트명은 사실 아무렇게나 작성해도 상관없지만, 저는 보통 접미사가 'Page'가 되게 짓는 편이에요! 이전에 지성님이 mypage/page.tsx 에서 하위 컴포넌트들 접미사를 'Section'으로 통일하신 거 보고 영감을 받아 저도 리뷰 페이지에서 이렇게 작성하게 된 것 같아요.
2. '~Section'라는 컴포넌트명을 가졌다고 해서 반드시 blocks 폴더에 넣을 필요는 없을 것 같아요!(domains/product/components에도 `FilterSection`처럼 ~Section으로 끝나는 컴포넌트가 있어요.)

2024-05-24 06:14 UTC, hyejinny97 commented on src/app/main/(detail)/products/[productId]/review/create/layout.tsx
> +      <form onSubmit={handleFormSubmit}>{progress === '1' ? badgeSelect : starRatingSelect}</form>
[Next Parallel Routing](https://nextjs.org/docs/app/building-your-application/routing/parallel-routes#examples) 방식을 사용했기 때문에 import하지 않아도 됩니다! 
이 방식을 사용하면 상황에 따라 조건적으로 route를 렌더링할 수 있습니다.

2024-05-24 07:29 UTC, hyejinny97 commented
충돌 해결한 후 다시 pr 올렸습니다. (#376)
이 pr은 close 할게요!

2024-05-24 07:30 UTC, closed without merging