✨ Feat : 상품 상세페이지 퍼블리싱
eco-dessert-platform/dessert-front pull request #380
Opened 2024-05-27 13:37 UTC by Wlfjd

## 이슈 번호

> #379 

## 작업 내용 및 테스트 방법

>

### 1. 상품 정보 탭 퍼블리싱 완료
https://github.com/eco-dessert-platform/dessert-front/assets/103630185/233ea021-6500-4e4d-8f2a-f47ebcd508c8

### 2. 뱃지 위치

디벨롭 풀 받으니 뱃지 에러 발생해서 위=> 아래로 수정했습니다

`import BADGE from '@/domains/review/constants/badge';`

`import { BADGE } from '@/domains/review/constants/badge';`

## To reviewers

1. 스토리북은 어디 기준으로 하면 좋을까요?
작은 컴포넌트 (ex)빵켓팅 알림 버튼 )을 기준으로 하면 좋을지 큰 단위 (뱃지영역, 주문가능일 영역) 으로 하면 좋을지 질문드리고 싶습니다

2. 상품 상세페이지 API 변경 예정이라 타입은 any로 설정하였습니다

2024-05-28 04:26 UTC, jijiseong requested changes

2024-05-28 04:26 UTC, jijiseong commented on src/shared/components/RepresentativeBadge.tsx
이 컴포넌트는 domains/review 에 있지 않나요?

2024-05-28 04:26 UTC, jijiseong commented on src/app/main/(detail)/products/[productId]/info/page.tsx
> +      <FixedPurchaseButtonSection data={data} />
page.tsx 에서는 전체적인 구조가 눈에 들어와야한다 생각하는데,
수정 전 코드가 더 가독성이 좋아보여요

2024-05-28 04:26 UTC, jijiseong commented on src/blocks/product/DetailContent/BriefExplanation.tsx
> +  data: IProductDetailType;
data, info 등의 네이밍은 의미가 불분명해요
productDetail 처럼 구체적인 변수 명을 사용하는게 좋아보입니다

2024-05-28 04:26 UTC, jijiseong commented on src/blocks/product/DetailContent/DetailContentItems.tsx
> +export default DetailContentItems;
API가 변경 예정이더라도 any는 금지입니다.
가독성이 너무 안좋아져요.

lint 에러 안뜨던가요?
설정이 잘 못 되어있는것 같네요
나중에 수정해둘게요!

2024-05-28 04:26 UTC, jijiseong commented on src/domains/product/components/DetailSectionWrapper.tsx
목적이 구역나누기,
block에서만 재사용되는 컴포넌트라
blocks/main/products/[productId]/info/common 으로 이동시키는게 좋아보여요

그리고 blocks랑 app 폴더 구조는 1대1 매칭 되어야해요

2024-05-28 04:26 UTC, jijiseong commented on src/domains/product/components/DetailInformationImgs.tsx
이것도 재사용성이 없어서
block으로 가는게 맞을것같아요

2024-05-28 04:26 UTC, jijiseong commented on src/domains/product/components/DetailSectionWrapper.tsx
> +);
className이 최상위 컴포넌트가 아닌곳에 들어가면 직관성이 떨어져요
className 뿐만 아니라 기본 HTML atrributes 들도요
`twMerge`는 두 개 이상의 className을 합칠때 사용해야해요

2024-05-28 04:26 UTC, jijiseong commented on src/domains/product/components/InfoWrapper.tsx
>  );
이것도요

2024-05-28 04:26 UTC, jijiseong commented on src/domains/product/components/ProductOptionsSection/index.tsx
이것도 blocks로 가야해요

2024-05-28 04:26 UTC, jijiseong commented on src/domains/product/components/ReviewBadgeSection/index.tsx
이것도요

2024-05-29 07:34 UTC, jijiseong commented
> 스토리북은 어디 기준으로 하면 좋을까요?
작은 컴포넌트 (ex)빵켓팅 알림 버튼 )을 기준으로 하면 좋을지 큰 단위 (뱃지영역, 주문가능일 영역) 으로 하면 좋을지 질문드리고 싶습니다

스토리북은 shared, domain 컴포넌트의 최상위 컴포넌트 기준으로 하면 좋을것 같습니다!

2024-05-29 12:59 UTC, Wlfjd commented on src/app/main/(detail)/products/[productId]/info/page.tsx
> +      <FixedPurchaseButtonSection data={data} />
수정 전은 페이지 파일은 좀 헤비한 것 같다고 느껴져서 전체적인 페이지의 윤곽틀만 보이게 헤더,메인,푸터 느낌으로 나누어봤습니다!

아니면 헤더와 구매버튼은 layout.tsx 로 분리한 뒤 DetailContent의 내용을 page.tsx에 작성하는 방법은 어떨까요??
```html
const Layout = () => (
  <>
    <Header
        title={`[${data.store.storeName}] ${data.board.title}`}
        content={
          <button type="button" aria-label="공유 버튼">
            <ShareIcon />
          </button>
        }
        back
      />
    {children}
   <FixedPurchaseButtonSection data={data} />
  </>
);

export default Layout;
```

2024-05-29 12:59 UTC, Wlfjd commented on src/blocks/product/ProductComposition.tsx
넵 현재는 안쓰지만 버전 업그레이드 되며 사용될 가능성이 있기에 삭제는 하지 않았습니다!

삭제하는게 좋을까요?..

2024-05-29 13:39 UTC, jijiseong commented on src/blocks/product/ProductComposition.tsx
음 그러면 일단 놔두는게 좋을것같네요
주석 처리는 굳이 안해도 되지 않나 생각이 듭니다!

2024-05-29 13:50 UTC, jijiseong commented on src/domains/product/components/ProductOptionsSection/index.tsx
네 맞아요
재사용성이 없고 구역을 나타내는 컴포넌트라서요

2024-05-29 22:03 UTC, Wlfjd commented on src/domains/product/components/DetailSectionWrapper.tsx
말씀하신대로 blocks 내의 `ReviewBadgeSection`과 `ProductOptionsSection`에서 재사용되고 사용되고 있어서 domains에 위치시키는게 맞지 않나요??

domain 폴더의 컴포넌트 목적은 재사용이라고 하셨는데 **products/[productId]/info/common**  와의 차이가 약간 애매한 것 같습니다ㅠ

그리고 blocks 하위에는 blocks/main/products/[productId] 가 없는데 blocks가 아니라 app을 의도하신건가요??

2024-05-30 09:32 UTC, jijiseong commented on src/domains/product/components/DetailSectionWrapper.tsx
> 말씀하신대로 blocks 내의 ReviewBadgeSection과 ProductOptionsSection에서 재사용되고 사용되고 있어서 domains에 위치시키는게 맞지 않나요??


이 컴포넌트는 전역적으로 재사용되는게 아니라 `ReviewBadgeSection, ProductOptionsSection` 에서만 재사용 되어서 domain 보다는 blcok/~~/common이 적합한것 같아요.
전역적으로 사용될 가능성도 없어보이고요

> 그리고 blocks 하위에는 blocks/main/products/[productId] 가 없는데 blocks가 아니라 app을 의도하신건가요??

block 입니다
block이랑 app 폴더 구조는 1대1 매칭 되어야해요

2024-06-02 10:03 UTC, jijiseong requested changes

2024-06-02 10:03 UTC, jijiseong commented on src/domains/product/components/TypeOfMonthlyOrder.tsx
typo만 가지고 있는 컴포넌트인가요?
너무 과한 컴포넌트 분리라고 생각돼요

2024-06-02 10:03 UTC, jijiseong commented on src/domains/product/components/InfoWrapper.tsx
이 컴포넌트도 위 [리뷰](https://github.com/eco-dessert-platform/dessert-front/pull/380/files#r1620344917)랑 같은 맥락입니다

2024-06-02 10:03 UTC, jijiseong commented on src/domains/product/components/OrderAvailableDays.tsx
이 컴포넌트도 재사용성이 없어요

2024-06-02 10:26 UTC, Wlfjd commented on src/domains/product/components/NutrientInfo.tsx
<img width="323" alt="image" src="https://github.com/eco-dessert-platform/dessert-front/assets/103630185/636e58f0-8b5a-4fa5-9396-373407195a21">
파란색 -> blocks
빨간색 -> domains

이렇게 생각했습니다..!
 빨간색 박스 3개가 하나의 옵션(blocks)을 구성하는 요소들이라서 domains의 색이 강하지 않을까 싶었어요! 이렇게 보기는 힘들까요??

2024-06-02 10:29 UTC, jijiseong commented on src/domains/product/components/NutrientInfo.tsx
빨간색 부분들도 block의 성격을 띄고있어요
재사용성 없고, 영역을 나타내서요

ProductOptionSection
  ㄴ index.tsx
  ㄴ IngredientInfo.tsx
  ㄴ OrderAvailableDays.tsx
  ㄴ NutrientInfo.tsx

  이런 구성이 좋을것 같아요

2024-06-02 10:32 UTC, Wlfjd commented on src/domains/product/components/TypeOfMonthlyOrder.tsx
"주문가능일" 항목의 경우는 주마다 다른 경우, 월마다 다른경우로 나뉘어질 예정이라(아래 노션처럼) 조건식 사용해서 TypeOfWeeklyOrder 또는 TypeOFMonthlyOrder 을 렌더링할 생각이었습니다!
TypeOFMonthlyOrder는 타이포만 가지고 있긴 하지만 부모컴포넌트에서의 가독성을 고려해서 이렇게 설계해봤어요!

+ 아니면 TypeOfWeeklyOrder와 TypeOFMonthlyOrder를 하나로 합칠까요?

<img width="698" alt="image" src="https://github.com/eco-dessert-platform/dessert-front/assets/103630185/134de7d8-e8a5-4708-8d49-b52ab1ae9ff9">

2024-06-02 11:59 UTC, jijiseong commented on src/domains/product/components/TypeOfMonthlyOrder.tsx
ProductOptionSection
ㄴ index.tsx
ㄴ IngredientInfo.tsx
ㄴ OrderAvailableDays.tsx
ㄴ NutrientInfo.tsx
ㄴ TypeOFMonthlyOrder.tsx
ㄴ TypeOfWeeklyOrder.tsx
이런식으로 ProductOptionSection 하위에서 private하게 관리하면 좋을 것 같아요

2024-06-02 12:01 UTC, jijiseong commented
yarn lock 파일 충돌 나는것 같은데, 
yarn lock은 새로운 패키지 설치나, 업데이트가 없으면 수정되면 안돼요

2024-06-02 12:55 UTC, Wlfjd commented on src/domains/product/components/TypeOfMonthlyOrder.tsx
`TypeOFMonthlyOrder`와 `TypeOfWeeklyOrder`는 orderAvailableDays 에서 사용되는 컴포넌트들이라 동일레벨에 있으면 안되지 않나요??

그렇다고 아래처럼 폴더화하는 건 뎁스가 넘 깊어지는거 아닌가싶습니다..ㅠㅠ

orderAvailableDays
ㄴindex.tsx
ㄴ TypeOFMonthlyOrder.tsx
ㄴ TypeOfWeeklyOrder.tsx

2024-06-02 13:11 UTC, jijiseong commented on src/domains/product/components/TypeOfMonthlyOrder.tsx
아 넵

OrderAvailableDays
ㄴ index.tsx
ㄴ TypeOFMonthlyOrder.tsx
ㄴ TypeOfWeeklyOrder.tsx

이 구조가 맞아요

depth가 너무 깊어진다고 생각하시면
TypeOFMonthlyOrder, TypeOfWeeklyOrder를 분리하지않고 OrderAvailableDays 에서 구현하셔도 될 것 같아요

2024-06-03 01:27 UTC, Wlfjd commented on src/domains/product/components/TypeOfMonthlyOrder.tsx
넵 우선 이렇게 구현하겠습니다
OrderAvailableDays
ㄴ index.tsx
ㄴ TypeOFMonthlyOrder.tsx
ㄴ TypeOfWeeklyOrder.tsx

2024-06-03 01:46 UTC, Wlfjd commented
> yarn lock 파일 충돌 나는데, yarn lock은 새로운 패키지 설치나, 업데이트가 없으면 수정되면 안돼요 이 브랜치에 있는 yarn lock 삭제하고, develop에 있는 yarn lock 파일 가져와서 yarn install 해보실래요?

1. 작업 브랜치의 yarn lock 삭제
2. develop의 yarn lock을 복사 후 작업브랜치에 붙혀넣기
3. yarn install

이 순서 맞나요?? 그리고 yarn install 을 하지 않으면 yarn dev가 실행이 안되더라고요ㅜ 그럴 경우에는 yarn install을 하고 pr 올릴 때는 수정된 파일을 yarn lock을 제외하고 업로드해도 되나요?

2024-06-03 06:19 UTC, jijiseong commented
> 이 순서 맞나요?? 그리고 yarn install 을 하지 않으면 yarn dev가 실행이 안되더라고요ㅜ 그럴 경우에는 yarn install을 하고 pr 올릴 때는 수정된 파일을 yarn lock을 제외하고 업로드해도 되나요?

yarn install 하면 yarn lock 파일을 기준으로 패키지를 설치하는데,
팀원들끼리 yarn lock 파일이 다르다면 다른 패키지가 설치되기때문에 
yarn lock을 제외하고 업로드하면 안돼요

2024-06-10 15:34 UTC, jijiseong commented on src/shared/queries/service.ts
혹시 이거 왜 protected로 바꾸셨나요?

2024-06-11 03:04 UTC, Wlfjd commented on src/shared/queries/service.ts
아 이거 fetchExtend 사용하면 baseUrl이 자동으로 붙는 줄 알고 제가 직접 get으로 api 연동하기 위해 외부 접근 가능하도록 변경했었던거에요! 근데 어제 arrow function으로 문제가 해결되어가지구 수정하겠습니다! 바로 커밋올릴게요

2024-06-11 07:20 UTC, merged