🐛 Fix :  mypage 401
eco-dessert-platform/dessert-front pull request #386
Opened 2024-05-30 13:10 UTC by jijiseong

## 이슈 번호

> ex) #이슈번호

## 작업 내용 및 테스트 방법

> 이번 PR에서 작업한 내용을 간략히 설명해주세요(이미지 첨부 가능)

어떤 경우인지 확실하게 잘 모르겠는데,
마이페이지 진입시에 401 error가 뜨는경우 json parse error가 떠서 수정 했습니다.

## To reviewers

2024-05-31 06:32 UTC, hyejinny97 requested changes

2024-05-31 06:32 UTC, hyejinny97 commented on src/app/error.tsx
이미 `global-error.tsx`가 있는데 app 폴더에 `error.tsx`을 생성하신 이유가 있으실까요??

2024-05-31 06:32 UTC, hyejinny97 commented on src/domains/user/queries/service.ts
> +        tags: [QUERY_KEY.profile]
QUERY_KEY 대신 user/queries/queryKey.ts에서 profileQueryKey 객체 생성해서 태그 지정해 주셔야할 것 같습니다!

2024-06-03 07:09 UTC, jijiseong commented on src/app/error.tsx
[next.js 공식 문서](https://nextjs.org/docs/app/building-your-application/routing/error-handling#handling-errors-in-root-layouts)에 따르면

error 페이지는 최상단의 layout.js, template.js 의 에러는 못잡고
global-error 페이지는 최상단의 layout.js, template.js 의 에러까지 잡는 차이가 있는데,

global-error 페이지가 있더라도 error 페이지를 정의하라고 추천하고있어요
이유는 error 페이지는 root layout을 포함하여 렌더링하기 때문에 UX상의 이점이 있기 때문이에요

2024-06-03 07:15 UTC, jijiseong commented
아 충돌도 해결하고 다시 리뷰오청 드릴게요

2024-06-04 05:40 UTC, hyejinny97 approved these changes

2024-06-04 05:40 UTC, hyejinny97 commented on src/app/error.tsx
> +      </div>
root layout과 함께 에러 페이지를 보여주기 위해 `error.tsx`를 따로 만드신 거라면,
'다시 시도하기', '홈으로 가기' 두 버튼을 fixed를 사용해 푸터 위로 띄우기 보단 block으로 두는 게 좋을 것 같아요!

2024-06-07 07:03 UTC, jijiseong commented on src/app/error.tsx
> +      </div>
대충 복붙만 했었는데 생각을 못했네요 

<img width="595" alt="image" src="https://github.com/eco-dessert-platform/dessert-front/assets/77661228/cd65361c-900e-4313-8606-b68b816cfeba">


저번에 해우님께서 요청하신 디자인대로 수정했습니다!

2024-06-08 02:55 UTC, merged