♻️ Refactor : 검색 페이지 API 수정
eco-dessert-platform/dessert-front pull request #396
Opened 2024-06-04 13:16 UTC by hyejinny97

## 이슈 번호

> ex) #이슈번호

close #393 

## 작업 내용 및 테스트 방법

> 이번 PR에서 작업한 내용을 간략히 설명해주세요(이미지 첨부 가능)

- 새로 변경된 API 컨벤션에 따라 검색 페이지 API를 전부 수정함 
- `revalidateTags.ts` 파일 삭제
- 'CORSOR' -> 'CURSOR' 오타 수정

## To reviewers

2024-06-06 20:15 UTC, jijiseong commented on src/app/search/(searchResult)/stores/page.tsx
> +    initialPageParam: 0
얘 -1아니고 0으로 초기화하는거 맞나요?

2024-06-06 20:16 UTC, jijiseong commented on src/app/search/(searchResult)/products/page.tsx
> +    initialPageParam: 0
여기도요!

2024-06-06 20:18 UTC, jijiseong commented on src/app/search/(searchResult)/stores/page.tsx
> +    initialPageParam: 0
INITIAL_CURSOR 사용해야 할 것 같아요!

2024-06-07 05:47 UTC, jijiseong requested changes

2024-06-07 05:47 UTC, jijiseong commented on src/app/mypage/review/page.tsx
>    });
저도 며칠전에 안건데
데이터를 직접 사용하는게 아니라면 `fetchInfiniteQuery` 말고 `prefechInfiniteQuery` 사용하는게 적합할 것 같아요
노션에도 업데이트 해두겠습니다!

2024-06-08 03:36 UTC, hyejinny97 commented on src/app/search/(searchResult)/stores/page.tsx
> +    initialPageParam: 0
검색 상품 API, 검색 스토어 API는 커서 기반이 아닌 아직 페이지 기반이더라구요!

2024-06-08 03:39 UTC, hyejinny97 commented on src/app/mypage/review/page.tsx
>    });
네네 말씀해주신 것처럼 next 서버에서 데이터를 직접 사용해야 한다면 `fetchQuery`를 써야겠지만, 
그게 아니라면 `prefetchQuery`를 사용하는 게 적합하겠네요.
검색 페이지 API랑 여기 API `prefetch`로 수정해서 푸시하겠습니다~

2024-06-08 17:55 UTC, jijiseong approved these changes

2024-06-08 17:55 UTC, jijiseong commented
고생하셨어요!

2024-06-08 17:56 UTC, merged