✨ Feat: 홈 화면 레이아웃 퍼블리싱
eco-dessert-platform/dessert-front pull request #399
Opened 2024-06-08 06:31 UTC by TaeyoonKwon

## 이슈 번호

>  #398 

## 작업 내용 및 테스트 방법

> 홈 화면 레이아웃 퍼블리싱 (상세 컴포넌트 및 API 작업 필요)

2024-06-09 19:17 UTC, jijiseong requested changes

2024-06-09 19:17 UTC, jijiseong commented on src/blocks/home/BestProductsSection/index.tsx
> +      <section className="flex justify-between">
```suggestion
    <PaddingWrapper className="flex justify-between">
```

depth를 줄여도 되지 않을까요?

2024-06-09 19:17 UTC, jijiseong commented on src/blocks/home/BestProductsSection/index.tsx
> +        </Link>
shared/constants/path.ts 의 `PATH` 상수를 사용하는게 좋을 것 같아요

2024-06-09 19:17 UTC, jijiseong commented on src/blocks/home/RecommendationSection/index.tsx
> +    >
이것도 `PATH` 상수를 사용하는게 좋을 것 같아요

2024-06-09 19:18 UTC, jijiseong requested changes

2024-06-09 19:18 UTC, jijiseong commented on src/blocks/home/BestProductsSection/index.tsx
> +      <section className="flex justify-between">
```suggestion
    <PaddingWrapper className="pb-[36px] flex justify-between">
```

depth를 줄여도 되지 않을까요?

2024-06-09 19:20 UTC, jijiseong commented on src/blocks/home/CategorySection/CategoryList.tsx
> +    <PaddingWrapper className={`grid pb-[0px] ${isCategoryTab ? 'grid-cols-3' : 'grid-cols-3'}`}>
`${isCategoryTab ? 'grid-cols-3' : 'grid-cols-3'}`
같은 값을 반환하고 있어요
실수 이신가요?

2024-06-09 19:56 UTC, jijiseong commented on src/blocks/home/BestProductsSection/index.tsx
> +      <section className="flex justify-between">
```suggestion
    <PaddingWrapper className="flex justify-between">
```

depth를 줄여도 되지 않을까요?

2024-06-11 07:02 UTC, hyejinny97 commented on src/blocks/home/RecommendationSection/index.tsx
> +        <div className="w-10 h-10 rounded-[10px] bg-[#F04C28] bg-opacity-15 flex justify-center items-center">
`tailwindcss.config.ts`에서 '#F04C28' 색상을 'primaryOrangeRed'로 설정해놔서 이걸 사용하시면 될 것 같아요!

2024-06-13 03:44 UTC, jijiseong approved these changes

2024-06-13 03:45 UTC, merged