✨ Feat: 상품카드 퍼블리싱 수정 & 스토리북 생성
eco-dessert-platform/dessert-front pull request #406
Opened 2024-06-12 03:30 UTC by Wlfjd

## 이슈 번호

> ex) #이슈번호

## 작업 내용 및 테스트 방법

>

- 하트 아이콘 변경된 디자인으로 적용
- 할인퍼센트, 별점/리뷰 추가
- typo 수정

<img width="839" alt="image" src="https://github.com/eco-dessert-platform/dessert-front/assets/103630185/9366524a-4101-4c8d-afe7-d78da1b92360">

## To reviewers

2024-06-12 08:29 UTC, hyejinny97 requested changes

2024-06-12 08:29 UTC, hyejinny97 commented on src/domains/product/components/ProductCard/ProductImage/index.tsx
> +        height={600}
기존 300에서 600으로 올리신 이유가 있으실까요??

2024-06-12 08:29 UTC, hyejinny97 commented on src/domains/product/components/ProductCard/ProductSummary/index.tsx
> +    <p className="typo-title-14-medium text-gray-900 leading-120 tracking-tight-4">
`leading-120 tracking-tight-4` 삭제 부탁드릴게요.

2024-06-12 08:29 UTC, hyejinny97 commented on src/domains/product/components/ProductCard/ProductSummary/index.tsx
> +      <span className="type-title-14-medium text-secondaryOrangeRed">10% </span>
`type` -> `typo` 오타 수정해주셔야 할 것 같아요

2024-06-12 13:44 UTC, Wlfjd commented on src/domains/product/components/ProductCard/ProductImage/index.tsx
> +        height={600}
300으로 설정하면 storybook에서 이렇게 가로너비가 435로 300을 초과하는 문제가 있어서 넉넉잡아 600으로 설정하였습니다! 
다른 좋은 방법 알고 계시면 공유해주세요~ㅠㅠ
<img width="1446" alt="image" src="https://github.com/eco-dessert-platform/dessert-front/assets/103630185/bd8b2598-c015-4c3f-be15-5f82cd26ef0b">

2024-06-12 13:48 UTC, Wlfjd commented on src/domains/product/components/ProductCard/index.stories.tsx
> +  </QueryClientProvider>
감싸지 않으면 이 에러가 발생해서 감쌌습니다
찾아보니 스토리북에 QueryClient 사용은 지양해야한다던데, 시도해도 아래 에러가 계속 발생해서 이렇게 구현해놓았어요!
안그래도 이부분 이번주 회의 때 공유하고 질문하고 싶었습니다 ㅎㅎ QueryClientProvider 사용하지 않는 해결 방법 알고 계시면 공유부탁드려요 혜진님! 
storybook error: no queryclient set, use queryclientprovider to set one

2024-06-13 03:33 UTC, hyejinny97 commented on src/domains/product/components/ProductCard/ProductImage/index.tsx
> +        height={600}
ProductImage width랑 height는 이전처럼 300으로 두고,
스토리에서 ProductCard를 `w-[40%]` 대신 `max-w-[300px]`로 두는 건 어떨까요??
실제 서비스에서 ProductImage의 너비 최댓값이 300px에 가까우니까 이 값을 유지하는 게 좋지 않을까 싶고,
스토리북에서도 실 서비스 이미지 크기와 유사하면 좋을 것 같아서요!

2024-06-13 06:37 UTC, hyejinny97 commented on src/domains/product/components/ProductCard/index.stories.tsx
> +  </QueryClientProvider>
여기 답변을 지금 봤네요..ㅎㅎ
스토리북에 QueryClient 사용을 지양해야하는 이유가 무엇인가요??

2024-06-14 10:19 UTC, Wlfjd commented on src/domains/product/components/ProductCard/index.stories.tsx
> +  </QueryClientProvider>
스토리북이 아니라 컴포넌트였던 것 같습니다!
이런 비슷한 내용의 블로그 참고했었어요 (https://toby2009.tistory.com/54)

2024-06-14 10:19 UTC, Wlfjd commented on src/domains/product/components/ProductCard/ProductImage/index.tsx
> +        height={600}
아 좋은 의견입니다! 그렇게 적용해볼게요 감사합니다~

2024-06-18 01:14 UTC, hyejinny97 approved these changes
수고하셨습니다!

2024-06-18 01:14 UTC, merged