✨ Feat: 상품 상세페이지 fake api -> 진짜 api 변경 & 디자인 수정
eco-dessert-platform/dessert-front pull request #407
Opened 2024-06-12 13:24 UTC by Wlfjd

## 이슈 번호

> ex) #이슈번호

> 
- api 변경된 부분 적용 
    - 주문가능일, 영양성분 데이터포멧팅 
- review 대표 뱃지 api 추가 
    - 기존엔 하드코딩 해놨었는데, review 뱃지 리스트에 따라 뱃지 렌더링되도록 수정
- 빵켓팅 액션 추가 (api 안나와서 동적 UI 구현만 해놓았습니다)
- 변경된 하트 아이콘 적용
- 이미지가 없을 때 이미지 카운터 제거

https://github.com/eco-dessert-platform/dessert-front/assets/103630185/f079f8d5-722a-4bcf-b7b9-284b9ecbe10f

https://github.com/eco-dessert-platform/dessert-front/assets/103630185/99fec6ec-c4c4-4b41-89f5-13cea0b73758

https://github.com/eco-dessert-platform/dessert-front/assets/103630185/46eb644a-a9f4-42f2-8ad6-b724ee247ea5

## To reviewers

2024-06-12 14:46 UTC, jijiseong requested changes
params의 productId는 string이 맞는데,
api로 받아온 데이터의 id는 number 타입으로 정의해야해요

2024-06-12 14:46 UTC, jijiseong commented on src/shared/hooks/useShakeAnimation.ts
> +export default useShakeAnimation;
함수명과 내부에서 하는 일이 일치하지 않아요
useToggle 사용하면 되지 않나요?

2024-06-12 14:46 UTC, jijiseong commented on src/domains/product/constants/formatDate.ts
> +// };
안쓰는 함수면 지워주세요

2024-06-12 14:46 UTC, jijiseong commented on src/blocks/main/(detail)/products/[productId]/info/ReviewBadgeSection.tsx
> +};
이 함수 쓸 필요없이
`badge.toLowerCase()` 사용하시면 돼요

2024-06-12 14:46 UTC, jijiseong commented on src/blocks/main/(detail)/products/[productId]/info/ProductOptionsSection/index.tsx
> +              <NutrientInfo nutrient={product.nutrient} />
내부에서 useGetProductDetailQuery를 호출하는게 깔끔할것 같아요

2024-06-12 14:46 UTC, jijiseong commented on src/blocks/main/(detail)/products/[productId]/info/ProductOptionsSection/OrderAvailableDays/index.tsx
> +        <BellButton isNotified={product.isNotified} />
```suggestion
      <div className="flex justify-between items-center">
        <div className="flex gap-[4px]">
          {product.orderType === "WEEK" && <TypeOfWeek availableDays={product.orderAvailableWeek} />}
          {product.orderType === "DATE" && <TypeOfWeek availableDays={product.orderAvailableWeek} />}
        </div>
      <BellButton isNotified={product.isNotified} />
```

2024-06-12 14:46 UTC, jijiseong commented on src/blocks/main/(detail)/products/[productId]/info/ProductOptionsSection/OrderAvailableDays/TypeOfDate.tsx
> +
이런 함수 만들어서 사용하지말고
Date 객체 사용해서 변환하는게 깔끔합니다

2024-06-12 14:46 UTC, jijiseong commented on src/blocks/main/(detail)/products/[productId]/info/ProductOptionsSection/NutrientInfo.tsx
> +import { ProductType } from '@/domains/product/types/productDetailType';
ProductType 타입 명 바꿔야할 것같아요
ProductDetailType아닌가요?

2024-06-12 14:46 UTC, jijiseong commented on src/blocks/main/(detail)/products/[productId]/info/FixedPurchaseButtonSection.tsx
> +  };
지역 변수 상태를 사용하면 페이지를 나갔다 들어오거나 하면 버그가 있을거예요
react-query 상태를 바꿔야해요
ProductCard 참고부탁드려요

2024-06-12 14:46 UTC, jijiseong commented on src/app/main/(detail)/products/[productId]/info/page.tsx
> +    <BoardDetailsSection productId={params.productId} />
useParams 사용해서 안 받아도 되는 props 줄이면 좋을 것 같아요

2024-06-13 07:13 UTC, Wlfjd commented on src/blocks/main/(detail)/products/[productId]/info/ProductOptionsSection/index.tsx
> +              <NutrientInfo nutrient={product.nutrient} />
```
 <IngredientInfo product={product} />
 <OrderAvailableDays product={product} />
```

이 것들도 마찬가지로 내부에서 호출하는게 나은가요?

2024-06-13 07:16 UTC, Wlfjd commented on src/app/main/(detail)/products/[productId]/info/page.tsx
> +    <BoardDetailsSection productId={params.productId} />
5개의 컴포넌트 모두에서 useParams 훅을 사용해야하는게 더 좋은 방식인가요??

2024-06-13 07:36 UTC, Wlfjd commented on src/blocks/main/(detail)/products/[productId]/info/ProductOptionsSection/OrderAvailableDays/TypeOfDate.tsx
> +
흠.. T를 기준으로 0번인덱스만 가져다 써야해서 이렇게 들어오는 데이터를 
```
"orderAvailableDate": {
          "startDate": "2024-06-01T22:35:34",
          "endDate": "2024-06-01T22:35:37"
        },
```
화면에 `2024.06.01 ~ 2024.06.01 `  이렇게 그리기 위해 문자열 변환만 하는거라 Date을 사용해서 변환하면 복잡해질 것 같다고 생각합니다! 
지성님이 생각하시는 Date 객체를 사용해서 변환하는 방법을 공유해주실 수 있으신가요?

2024-06-13 07:41 UTC, jijiseong commented on src/blocks/main/(detail)/products/[productId]/info/ProductOptionsSection/index.tsx
> +              <NutrientInfo nutrient={product.nutrient} />
넵 맞아요
리액트 쿼리로 상태관리를 할 수 있는데
props로 전달하면 쓰는 의미가 없어지는것 같아서요

2024-06-13 07:54 UTC, jijiseong commented on src/blocks/main/(detail)/products/[productId]/info/ProductOptionsSection/OrderAvailableDays/TypeOfDate.tsx
> +
```ts
new Date("2024-06-01T22:35:37").toLocaleDateString('ko-KR');
```
이런식으로 쓰면 변환할 수 있어요!

2024-06-13 07:57 UTC, jijiseong commented on src/blocks/main/(detail)/products/[productId]/info/ProductOptionsSection/NutrientInfo.tsx
> +import { ProductType } from '@/domains/product/types/productDetailType';
IProductType 이랑 변수명이 겹쳐서 별로인 것 같아요
```ts
export interface IDetailProductType {
  boardIsBundled: true;
  products: {
    id: number;
    title: string;
    glutenFreeTag: boolean;
    highProteinTag: boolean;
    sugarFreeTag: boolean;
    veganTag: boolean;
    ketogenicTag: boolean;
    nutrient: {
      sugars: number;
      protein: number;
      carbohydrates: number;
      fat: number;
      weight: number;
      calories: number;
    };
    orderType: string;
    orderAvailableDate: {
      startDate: string;
      endDate: string;
    };
    orderAvailableWeek: {
      monday: boolean;
      tuesday: boolean;
      wednesday: boolean;
      thursday: boolean;
      friday: boolean;
      saturday: boolean;
      sunday: boolean;
    };
    isNotified: boolean;
  }[];
}
```
```
IDetailProductType["products"] 또는 Pick<IDetailProductType, "products">
```

이런식으로 쓰시는게 어떨까요

2024-06-13 08:02 UTC, Wlfjd commented on src/blocks/main/(detail)/products/[productId]/info/ProductOptionsSection/index.tsx
> +              <NutrientInfo nutrient={product.nutrient} />
근데 이 코드가 map을 사용해서 요소하나하나를 넣어주고 있는게 특징인데 컴포넌트 내부에서 호출하게 되면 map으로 못돌리지 않나요?


```html
  return (
    <DetailSectionWrapper title="상품 옵션">
      {productData?.products.map((product: ProductType) => (
        <div key={product.id}>
          <CategoryOption onClick={() => handleCategoryClick(product.id)} option={product} />
          {activeOption[product.id] && (
            <PaddingWrapper className="flex flex-col gap-4">
              <IngredientInfo product={product} />
              <OrderAvailableDays product={product} />
              <NutrientInfo nutrient={product.nutrient} />
            </PaddingWrapper>
          )}
        </div>
      ))}
    </DetailSectionWrapper>
  );
```

2024-06-13 08:33 UTC, jijiseong commented on src/blocks/main/(detail)/products/[productId]/info/ProductOptionsSection/index.tsx
> +              <NutrientInfo nutrient={product.nutrient} />
아하 products 그대로 전해주는건줄 알았네요

그럼 props를  product로 객체 하나로 받지말고
요소 하나하나 받는게 좋을것 같아요
NutrientInfo  처럼요

2024-06-13 08:33 UTC, jijiseong commented on src/blocks/main/(detail)/products/[productId]/info/ProductOptionsSection/NutrientInfo.tsx
> +import { ProductType } from '@/domains/product/types/productDetailType';
export interface DetailBoard {
  boardIsBundled: true;
  products: ProductDetailType[];
}

이런식이 맞는것 같네요

2024-06-13 08:34 UTC, jijiseong commented on src/app/main/(detail)/products/[productId]/info/page.tsx
> +    <BoardDetailsSection productId={params.productId} />
hook으로 props를 줄일 수 있으면 줄이는게 좋다 생각해요

2024-06-13 08:36 UTC, jijiseong commented on src/blocks/main/(detail)/products/[productId]/info/ProductOptionsSection/NutrientInfo.tsx
> +import { ProductType } from '@/domains/product/types/productDetailType';
그리고 변수명도 productDetails가 더 명확할것 같아요

2024-06-13 09:55 UTC, Wlfjd commented on src/blocks/main/(detail)/products/[productId]/info/ProductOptionsSection/NutrientInfo.tsx
> +import { ProductType } from '@/domains/product/types/productDetailType';
지금까지 타입 작명은 **I~Type** 으로 했는데 이렇게 변경하는게 맞다고 생각하시는 이유가 궁금합니다~!

2024-06-14 06:35 UTC, Wlfjd commented on src/app/main/(detail)/products/[productId]/info/page.tsx
> +    <BoardDetailsSection productId={params.productId} />
그럼 이 5개의 컴포넌트들을 다 클라이언트로 변경해야하는데 모든 컴포넌트를 클라이언트로 변경하면 next의 이점이 사라지지 않나요??

2024-06-14 09:04 UTC, closed without merging