✨ Feat : 리뷰 수정 / 작성
eco-dessert-platform/dessert-front pull request #427
Opened 2024-06-24 17:44 UTC by jijiseong

## 이슈 번호

> ex) #이슈번호

## 작업 내용 및 테스트 방법

> 이번 PR에서 작업한 내용을 간략히 설명해주세요(이미지 첨부 가능)

1. 리뷰 작성

2. 리뷰 수정

### 병렬라우팅 삭제
기존에 병렬라우팅으로 구현되어 있었는데,
컴포넌트 재사용성을 높이기 위해서 병렬 라우팅을 없애고 컴포넌트로 분리했습니다.
defaultValues, onSumit을 props로 받는 `ReviewCreatForm`으로 분리했습니다.

### `progress` searchParams -> params
layout 에서 useSearchParams를 강제로 사용하여 client component로 사용해야하는 불편함 때문에 params로 수정했습니다.

## To reviewers

2024-06-25 12:13 UTC, jijiseong commented
라우팅 경로가 직관적이지 않아 보여서, searchParams -> params 바꾼 부분 다시 searchParams로 수정할 예정입니다.
상품 상세 - 리뷰 작업 브랜치에서 해둘게요.

2024-06-25 12:47 UTC, jijiseong commented
params를 사용할 때, 라우팅 경로가 직관적이지 않아서 다시 searchParams로 바꿀 예정입니다.
상품 상세 - 리뷰탭 작업 브랜치에서 해둘게요.

2024-06-27 07:51 UTC, hyejinny97 requested changes
'react-hook-form'을 사용하면 이렇게 깔끔하게 작성할 수 있군요!
덕분에 많이 배우고 갑니다..😊

2024-06-27 07:51 UTC, hyejinny97 commented on src/app/main/(detail)/products/[productId]/review/[reviewId]/update/[progress]/page.tsx
> +  console.log(watch('images'));
여기 삭제 부탁드립니다~

2024-06-27 07:51 UTC, hyejinny97 commented on src/app/main/(detail)/products/[productId]/review/[reviewId]/update/[progress]/page.tsx
> +        title="리뷰 작성"
"리뷰 수정"으로 변경해주셔야할 것 같아요

2024-06-27 07:51 UTC, hyejinny97 commented on src/domains/review/components/common/StarRating/index.tsx
> +    onRatingChange,
`onChange`와 `onRatingChange` 두 함수의 차이가 뭔가요??

2024-06-27 07:51 UTC, hyejinny97 commented on src/domains/review/queries/useImageUploadMutation.ts
> +    mutationKey: key,
`mutationKey` 값을 여기서 바로 지정하지 않고 인자로 받는 이유가 있으신가요??

2024-06-27 07:51 UTC, hyejinny97 commented on src/shared/queries/service.ts
> +        ...(form ? {} : { 'Content-Type': 'application/json' }),
`form=true`일 때 Content-Type 값을 `multipart/form-data`가 아닌 위처럼 설정하신 이유가 있나요?

2024-06-27 13:47 UTC, jijiseong commented on src/domains/review/components/common/StarRating/index.tsx
> +    onRatingChange,
`onChange` 는 input의 기본 attribute이고,
`onRatingChange`는 value의 변화에 반응하여 `value(rating)`을 인자로 전달해주는 함수인데,

onRatingChange를 사용할 경우 `react-hook-form`의 `register`사용이 안되기떄문에 onChange를 연결 해주었습니다!

필요에 따라 onRatingChange, onChange 둘중 하나를 선택해서 사용하면 됩니다!

2024-06-27 13:49 UTC, jijiseong commented on src/domains/review/queries/useImageUploadMutation.ts
> +    mutationKey: key,
`mutationKey`를 통해 업로드 요청 후 응답받은 이미지 url을 알 수 있는데,
ImageUpload API를 리뷰 업로드할때 뿐만 아니라 
다른 곳에서도 사용할 수 있다고 생각해서
재사용성을 높이기 위해서 key를 인자로 전달받도록 해뒀어요

2024-06-27 13:52 UTC, jijiseong commented on src/shared/queries/service.ts
> +        ...(form ? {} : { 'Content-Type': 'application/json' }),
`multipart/form-data` 를 직접 넣어주면, boundary 값이 뒤에 안 붙어서 에러가 나더라고요
빈 상태로 두면 `FormData` 객체를 전송할때 자동으로 `Content-Type: multipart/form-data; boundary ~~~` 형식으로 들어가요

2024-06-28 02:22 UTC, hyejinny97 commented on src/domains/review/components/common/StarRating/index.tsx
> +    onRatingChange,
`StarRating` 컴포넌트 안에 있는 input 요소의 onChange 값을 `onChange`로 바꿔놓으셨던데, 
그러면 `StarRating`의 prop으로 `onRatingChange`를 사용한다고 해도 어차피 동작하지 않지 않나요??
(위 스토리북 링크 들어가서 확인하니 Editable일 때 동작하지 않네요)

`onRatingChange`는 삭제하고 `onChange`만 사용해도 될 것 같아요

2024-07-01 10:12 UTC, jijiseong commented on src/domains/review/components/common/StarRating/index.tsx
> +    onRatingChange,
input을 제어할 때, props의 value가 바뀐다고 착각했네요
삭제 해둘게요!

2024-07-01 11:27 UTC, hyejinny97 approved these changes
수고하셨습니다!

2024-07-01 11:27 UTC, merged