✨ Feat : 홈페이지 UI 수정, API 연동
eco-dessert-platform/dessert-front pull request #428
Opened 2024-06-26 09:59 UTC by hyejinny97

## 이슈 번호

> ex) #이슈번호

close #398 

## 작업 내용 및 테스트 방법

> 이번 PR에서 작업한 내용을 간략히 설명해주세요(이미지 첨부 가능)

### 1. 홈페이지 UI 수정, API 연동 (3차 스프린트)

- 로그인 여부에 따라 서로 다른 UI를 보여줌
  
  - 비로그인 시 '맞춤 추천 받으러가기' 버튼 + '인기 상품' 목록을 보여줌
  - 로그인 시 '개인 맞춤 상품' 목록을 보여줌

<img src='https://github.com/eco-dessert-platform/dessert-front/assets/98448226/be70c4b3-ca9b-4bba-b84d-66d1121a0f57' width='400' />
<img src='https://github.com/eco-dessert-platform/dessert-front/assets/98448226/372ed8d9-c12a-4b0c-8585-4f2f618424f4' width='400' />

- 사용자가 선택한 선호도(preference)에 따라 안내 문구가 나옴
   
   ```
   근성장을 위한 고단백 상품과
   체질•알러지를 위한 글루텐프리 상품을 모아봤어요!
   ``` 

- 기존 `getBestProducts` -> `useGetAllProductsQuery`로 변경

  - 자동로그인 후 서버로 다시 요청해 '개인 맞춤 상품' 데이터를 얻기 위해, queryKey에 `recommeded: isLoggedIn`을 추가했음 

```js
export const useGetAllProductsQuery = (query: IFilterType) => {
  const isLoggedIn = useRecoilValue(isLoggedinState);
  const queryKey = [...productQueryKey.list('home'), { filter: query, recommended: isLoggedIn }];
  ...
};
```

### 2. preference 코드 수정

- preference 관련 코드를 profile로부터 분리

  - `user/atoms/preference.ts` 생성
  - `user/types/preference.ts` 생성 

- atom preferenceState 값을 한글로 변경
  
  - 기존 `['muscle grow', 'diet']` -> `['근성장', '다이어트']` 

### 3. 메인 상품 페이지, 검색 상품 페이지 스켈레톤 이슈 해결

- 이슈) 상품 페이지에서 스크롤을 내려 마지막 상품에 다다랐을 때, 기존 상품 카드가 사라지고 화면 전체에 스켈레톤이 나타나는 이슈가 있었음
- 원인) `if (isFetching)` 조건문을 충족하면서 `<SkeletonProductCardList />`가 반환 됐기 때문
- 해결) `if (isFetching && !isFetchingNextPage)`로 변경

### 4. 조사(-이/-가, -을/-를, -은/-는, -와/-과) 체크 함수 생성

- 조사 앞 문자에 받침이 있으면 '은/이/을/과'를 반환, 없으면 '는/가/를/와'를 반환

```js
const checkPostPosition = (
  word: string,
  postPosition: '은' | '는' | '이' | '가' | '을' | '를' | '과' | '와'
) => {
  ...
  return word + correctedPostPosition;
};
``` 

- 사용법

```js
checkPostPosition(preference, '를')
``` 

### 5. `SkeletonProductCardList`에서 PaddingWrapper 제거

- 기존

```js
const SkeletonProductCardList = ({ row = 3, col = 2 }: SkeletonProductCardListProps) => (
  <PaddingWrapper className={...}>
    ...
  </PaddingWrapper>
);
```

- 변경

```js
const SkeletonProductCardList = ({ row = 3, col = 2 }: SkeletonProductCardListProps) => (
  <div className={...}>
    ...
  </div>
);
```
## To reviewers

2024-07-01 10:01 UTC, jijiseong requested changes

2024-07-01 10:01 UTC, jijiseong commented on src/shared/utils/checkPostPosition.ts
> +export const checkPostPosition = (
함수명만 보면 boolean을 반환하는 것 같아요.
attachPostPosition 같은건 어떨까요

2024-07-01 19:46 UTC, jijiseong commented on src/shared/utils/checkPostPosition.ts
> +export const checkPostPosition = (
`checkPostPosition("지성", "는")`의 반환값은 `지성은` 아닌가요?
"지성"과 "는"을 기반으로 올바른 조사를 붙여주는 함수라고 생각했어요

2024-07-02 03:52 UTC, hyejinny97 commented on src/shared/utils/checkPostPosition.ts
> +export const checkPostPosition = (
네네 그렇게 볼 수도 있겠네요
지성님 말씀대로 `checkPostPosition`은 함수명만 보고 어떤 타입의 값을 반환해줄지 명확하게 알 수 있을 것 같진 않네요.
`attachPostPosition`으로 수정해 놓을 게요!

2024-07-04 03:39 UTC, jijiseong approved these changes

2024-07-04 03:39 UTC, merged